### ISSUE TITLE
متن کامل ارور وقتی فایل تستی که خودتون گذاشتین رو اجرا میکنم

### ISSUE THREAD

**Issue by donmoderato** [mirsaeedi/SQLCLR-PersianCalendar#1]
Msg 10314, Level 16, State 11, Line 1
An error occurred in the Microsoft .NET Framework while trying to load assembly id 65536. The server may be running out of resources, or the assembly may not be trusted with PERMISSION_SET = EXTERNAL_ACCESS or UNSAFE. Run the query again, or check documentation to see how to solve the assembly trust issues. For more information about this error: 
System.IO.FileLoadException: Could not load file or assembly 'sqlclr.jalalidateutility, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The given assembly name or codebase was invalid. (Exception from HRESULT: 0x80131047)
System.IO.FileLoadException: 
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean forIntrospection)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)
   at System.Reflection.Assembly.Load(String assemblyString)

**Comment by mirsaeedi** [comment]
Would you please report the SQL Server version you are using?

**Comment by donmoderato** [comment]
Yes,sql server 2012

**Comment by donmoderato** [comment]
Hello,do you find any reason?please help me

**Comment by donmoderato** [comment]
Hi Mr Mirsaeedi
Would you please help me,i prefer to use your function.

**Comment by mirsaeedi** [comment]
@donmoderato I'm working on the problem. I reach you back by tomorrow.

**Comment by mirsaeedi** [comment]
based on my investigation, the error you get has nothing to do with "SQLCLR-Jalali-Date" itself. You could find the solution on Google or stackoverflow, if you searched for the error.

Have a look at [this](https://www.thedummyprogrammer.com/clr/sql-server-error-using-a-database-with-a-clr-assembly) or other similar articles that have provided a solution for the exact error.

Possibly, just running the following script could do the fix. 
```sql
ALTER DATABASE MyDatabaseName SET TRUSTWORTHY ON
```

**Comment by donmoderato** [comment]
I didn't find any solution for this problem,unfortunately.

**Comment by mirsaeedi** [comment]
Did you try to turn on the TRUSTWORTHY on your database?

**Comment by donmoderato** [comment]
Yes,but the error didn't obviate

**Comment by donmoderato** [comment]
The closer things that i found was this
https://www.google.com/url?sa=t&source=web&rct=j&url=https://support.microsoft.com/hr-ba/help/949080/error-message-when-you-execute-a-clr-routine-or-use-an-assembly-in-sql&ved=2ahUKEwiMnIiVpoTjAhXOCOwKHeh5BUkQFjABegQIBhAJ&usg=AOvVaw2xr0vpxYbYQ02EiPTkEugs&cshid=1561492499736

But i didn't reach any result,would you plesse tell me what do you get?
